# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

before_install:
  - sudo apt-get update

sudo: required

r:
  - release

addons:
  apt:
    packages:
      - libv8-dev

after_success:
  - Rscript -e 'covr::codecov()'


