#' Make markdown files for talks
#'
#' This function will create markdown files in the Hugo Academic style for talks
#' specified in an Excel spreadsheet, CSV file, or Google Sheet.
#'
#' @param data The location of the file containing your data. Can be a path to a
#'   local Excel/CSV file, or the URL of a Google Sheet.
#' @param sheet_name Defines the sheet from which to read information on talks.
#'   Default is "talks"
#' @param dir The directory you would like the markdown documents to be saved in
#' @param folder Create each record within it's own folder in the main directory
#'   (TRUE), or simply create the files (FALSE). Default is TRUE
#' @param create Logicial. If the specified directory doesn't exists, should it
#'   be created? Default is TRUE.
#' @export
make_talk_md <- function(data,
                         sheet_name = "talks",
                         dir = "./content/talk",
                         folder = TRUE,
                         create = TRUE
                         ) {

  # Get import file type and import data
  if (tools::file_ext(data) %in% c("csv","xlsx", "xls")) {
    d <- rio::import(data, which = sheet_name)
  } else {
    googlesheets4::sheets_deauth()
    d <- googlesheets4::read_sheet(data, sheet = sheet_name)
  }

  # Add preprocessing of tags

  for (row in 1:nrow(d)) {

    # Reformat tags
    if (!is.na(d$tags[row])) {
      d$tags[row] <-
        paste(trimws(unlist(stringr::str_split(d$tags[row], ","))), collapse = "\",\"")
      d$tags[row] <- gsub(" ", "-",d$tags[row])
    } else  {
      d$tags[row] <- ""
    }

    if (is.na(d$selected[row])) {
      d$selected[row] <- "false"
    }

    if (d$all_day[row]==TRUE) {
      d$time_start[row] <- "T00:00:00"
    } else {
      d$time_start[row] <- paste0("T",d$time_start[row])
      d$time_end[row] <- paste0("T",d$time_end[row])
    }

  }



  d$all_day <- tolower(as.character(d$all_day))

  d$selected <- tolower(as.character(d$selected))



  md <- glue::glue_data(d, {
    "+++
## Generated by the R package lazyacademic
## Do not edit directly, edit the Google Sheet [id = <<data>>]


date = \"<<date>><<time_start>>\"
all_day = <<all_day>>
date_end = \"<<date>><<time_end>>\"


abstract = \"<<abstract>>\"
title = \"<<title>>\"

event = \"<<event>>\"
event_url = \"<<event_url>>\"
location = \"<<location>>\"

tags = [\"<<tags>>\"]
math = true
selected = <<selected>>
project = [\"<<project>>\"]

url_slides = \"<<url_slides>>\"
url_video = \"<<url_video>>\"


[header]
  image = \"<<image_path>>\"
  caption = \"<<image_caption>>\"

+++
"
  }, .na = "", .open = "<<", .close = ">>")

  # Check if specified directory exists, if not, create it

  if (dir.exists(dir)) {
    message("Editing directory: ", dir)
  } else {
    if (create == TRUE) {
      message("Creating directory: ", dir)
      dir.create(file.path(dir), recursive = TRUE)
    } else {
      stop("Specified directory doesn't exist: ", dir,
           "\n  Use the `create = TRUE` argument to create the directory.")
    }
  }


  file_base <- paste0("talk-", d$talk_id)
  file_name <- glue::glue("{dir}/{file_base}.md")
  purrr::walk2(md, file_name, writeLines)
}
