#' Make markdown files for talks
#'
#' This function will create markdown files in the Hugo Academic style for talks
#' specified in a Google Sheet.
#'
#' @param dir The directory you would like the markdown documents to be saved in
#' @param id Your Google Sheet id
#' @export
make_talk_md <- function(dir, id = "1-PItelqpv0Sb_LdiEDqb8O3D_Roii5nVTL07IRVbRtA") {
  gs <- googlesheets::gs_key(id, lookup = TRUE, verbose = FALSE)
  d <- suppressMessages(googlesheets::gs_read(gs, verbose = FALSE))
  d <- d[d$manual == 0, ]
  d$time_start <- glue::glue_data(d, "{when}-01-01T12:00:00")
  d$time_end <- glue::glue_data(d, "{when}-01-01T13:00:00")
  md <- glue::glue_data(d, {
    "+++
## Generated by the R package lazyacademic
## Do not edit directly, edit the Google Sheet [id = (id)]
title = \"(title)\"
event = \"(where)\"
time_start = (time_start)
time_end = (time_end)

url_custom = [{name = \"Link\", url = \"(link)\"}]
+++
"
  }, .open = "(", .close = ")")
  file_base <- tolower(gsub(" ", "_", d$where))
  file_name <- glue::glue("{dir}/{file_base}.md")
  purrr::walk2(md, file_name, writeLines)
}
