#' Make markdown documents for publications
#'
#' This function will create markdown documents in the Hugo Academic style for papers
#' specified in a Google Sheet.
#'
#' @param data The URL or a Sheet ID, which ident
#' @param dir The directory you would like the markdown documents to be saved
#'   in. Defaults to the correct folder for publication files when using the
#'   Hugo Academic blogdown template.
#' @param create Logicial. If the specified directory doesn't exists, should it
#'   be created? Default is TRUE.
#' @export
#'
make_paper_md <- function(data, dir = "./content/publication", sheet_name = "papers", create = TRUE) {

  if (tools::file_ext(data) %in% c("csv","xlsx", "xls")) {
    d <- rio::import(data, which = sheet_name)
  } else {
    googlesheets4::sheets_deauth()
    d <- googlesheets4::read_sheet(data, sheet = sheet_name)
  }

  for (row in 1:nrow(d)) {

  # Reformat tags
  if (!is.na(d$tags[row])) {
  d$tags[row] <- paste(trimws(unlist(stringr::str_split(d$tags[row], ","))),collapse = "\",\"")
  d$tags[row] <- gsub(" ", "-",d$tags[row])
  } else  {
  d$tags[row] <- ""
  }

  # Seperate authors by comma,
  d$authors[row] <- paste(trimws(unlist(stringr::str_split(d$authors[row], ","))),collapse = "\",\"")

  }

  # Create md text
  md <- glue::glue_data(d, {
    "+++
## Generated by the R package lazyacademic
## Do not edit directly, edit the Google Sheet (id = <<data>>)

title = \"<<title>>\"
date = <<date>>
authors = [\"<<authors>>\"]
publication_types = [\"<<pub_type>>\"]

publication = \"<<publication>>\"

abstract = \"<<abstract>>\"

selected = <<tolower(selected)>>
featured = <<tolower(featured)>>

doi = \"<<doi>>\"

url_pdf = \"<<url_pdf>>\"
url_preprint = \"<<url_preprint>>\"
url_code = \"<<url_code>>\"
url_dataset = \"<<url_dataset>>\"
url_project = \"<<url_project>>\"
url_slides = \"<<url_slides>>\"
url_video = \"<<url_video>>\"
url_poster = \"<<url_poster>>\"
url_source = \"<<url_source>>\"

tags = [\"<<tags>>\"]
math = true
highlight = true
[header]
image = \"\"
caption = \"\"
+++"
  }, .na = "", .open = "<<", .close = ">>")

  # Check if specified directory exists, if not, create it

  if (dir.exists(dir)) {
    message("Editing directory: ", dir)
  } else {
    if (create == TRUE) {
      message("Creating directory: ", dir)
      dir.create(file.path(dir), recursive = TRUE)
    } else {
      stop("Specified directory doesn't exist: ", dir,
           "\n  Use the `create = TRUE` argument to create the directory.")
    }
  }

  # Create filenames
  file_base <- purrr::map_chr(d$bib, ~ strsplit(.x, '[{,]')[[1]][2])
  file_name <- glue::glue("{dir}/{file_base}.md")

  # Provide messages about changes
  for (file in 1:length(file_name)) {
    if (file.exists(file_name[file])) {
      message(paste0("Updating existing publication: ", file_base[file]))
    } else {
      message("Creating new publication: ", file_base[file])
    }
  }

  # Write new files
  purrr::walk2(md, file_name, writeLines)

}
